import { useEffect, useState } from "react";
import Head from "next/head";
import tw from "tailwind-styled-components";
import Web3 from "web3";

const Container = tw.div`
    flex
    justify-center
    items-center
    w-full
    bg-pink-300
`;

const Button = tw.button`
    btn
    btn-primary
    w-64
    mt-12
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <h1 className="font-bold">Your wallet address is 0x...c0c0</h1>
      {/* <h1 className="font-bold">Your wallet is {walletAddress}</h1> */}
    </>
  );
}
