import Head from "next/head";
import styles from "@/styles/Home.module.css";
import tw from "tailwind-styled-components";

const Container = tw.div`
    flex
    justify-center
    items-center
    w-full
    bg-indigo-600
`;

const Button = tw.button`
    btn
    btn-primary
    w-64
    mt-12
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main className={styles.main}>
          <h1 className="text-3xl font-bold underline">Hello World!</h1>
          <Button>Daisy UI Button</Button>
        </main>
      </Container>
    </>
  );
}
