import { ReactNode, useEffect, useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import tw from "tailwind-styled-components";
import Web3 from "web3";
import Footer from "@/components/organism/footer/Footer";
import Navbar from "@/components/organism/Navbar/Navbar";

const Container = tw.div`
    flex
    justify-center
    items-center
    w-full
    bg-pink-300
`;

const Content = tw.div`
    flex
    flex-1
    justify-center
    p-8
`;

const PrimaryLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Grappa Toy Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Content>{children}</Content>
        <Footer />
      </main>
    </>
  );
};

export default PrimaryLayout;
